version: 2.1
Commands:
  print_pipeline_id:
    description: "command to print out pipeline id"
    parameters:
      id:
        type: string
    steps:
      -  run: echo << parameters.id >>
jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "text to output here" > output.txt
      - persist_to_workspace: 
          root: ~/
          paths:
            - output.text
  print_output_file:
    docker:
      - image: circle/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

workflows:
  my_workflows:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - print_pipeline_id
          
